[package]
name = "aetheris-brain"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = "0.8"                                # Versi 2026
serde = { version = "1.0", features = ["derive"] }
